Console.WriteLine("Input double a:");
double a = double.Parse(Console.ReadLine());
Console.WriteLine("Input double b:");
double b = double.Parse(Console.ReadLine());
Console.WriteLine("Input double c:");
double c = double.Parse(Console.ReadLine());
Console.WriteLine("Input double d:");
double d = double.Parse(Console.ReadLine());
double x = (a + 2 * b - c + d) / (c * d) + (a + b) / (c - d) - a * a / (b * b);
Console.WriteLine($"x = {x}");
double y = 5 * (a + b) * (c - d) / (1 / 2.0 * c) + d * d * ((a * a - b * b) / (b - a));
Console.WriteLine($"y = {y}");
double z = (Math.Pow((x * x - 2 * x), 3) - 4 * (Math.Pow(x, 4) + 1) * (1 - b)) / (5 * a + 3 * b);
Console.WriteLine($"z = {z}");
double r = (1 / 2.0 * a + 3 / 4.0 * b - 7 / 5.0) / (3 * c + 1) + 1.0 / (a - c);
Console.WriteLine($"r = {r}");
